import { Link } from "wouter";

type Images = Record<string, string>;
const Pill = ({ children, tone = "statement" }: { children: React.ReactNode; tone?: string }) => <span className={`pill pill-${tone}`}>{children}</span>;
const Head = ({ n, children, lead }: { n: string; children: React.ReactNode; lead?: string }) => <div className="sec-head"><span className="sec-idx">{n}</span><h2>{children}</h2>{lead && <p className="sec-lead">{lead}</p>}</div>;

const paths = [
  ["I am a brand or procurement team", "Compliant, technically suitable material with documentation your audit can read.", "Brand program page →", "/industries/apparel-brands/"],
  ["I am a garment exporter or factory", "Less sourcing friction, verified fabric and local delivery to your line.", "Exporter program page →", "/industries/garment-exporters/"],
  ["I am a buying house", "Comparison-ready options and documentation for the brands you serve.", "Buying-house program page →", "/industries/buying-houses/"],
  ["I need a technical material", "Functional fabric or yarn specified by test method and acceptance target.", "Functional library →", "/products/functional-technical/"],
];
const cats = [
  ["Woven Fabrics", "9 records · Poplin to canvas — precision-woven constructions for shirt, uniform and workwear programs.", "woven", "/products/woven-fabrics/"],
  ["Knit Fabrics", "7 records · Jersey to sherpa — looped constructions for T-shirts, activewear, fleece and fashion programs.", "knit", "/products/knit-fabrics/"],
  ["Denim Fabrics", "5 records · Regular to coated — indigo twill systems for jeans, workwear and fashion denim programs.", "denim", "/products/denim-fabrics/"],
  ["Sportswear & Activewear Fabrics", "4 records · Yoga, swim, gym and functional stretch — 4-way performance constructions for movement programs.", "activewear", "/products/sportswear-activewear/"],
  ["Functional & Technical Fabrics", "5 records · Antibacterial, waterproof, fireproof, high-strength and recycled — performance with evidence.", "functional", "/products/functional-technical/"],
  ["Functional / Performance Yarns", "6 records · Coolmax-type, antibacterial, waterproof, fireproof, high-strength and super-soft yarn systems.", "yarns", "/products/performance-yarns/"],
];
const why = [["China-connected mill access", "Direct, partner and cooperative mill relationships across China’s weaving, knitting and finishing regions — with the relationship type stated for every option we recommend."], ["Bangladesh execution", "Import, customs coordination, local distribution and factory delivery from Uttara, Dhaka — with the responsibility for each step written into your order file."], ["Two-stage quality verification", "Inline inspection at the source mill and final pre-shipment verification, against acceptance criteria you approve — a process, not a slogan."], ["Specification-led service", "We start from construction, composition, weight, width, finish, application or a reference sample — and we answer with data sheets, samples and evidence, not adjectives."]];
const route = [["Fabric brief", "You + YOU LI", "Construction, target spec, quantity, timeline and compliance requirements — or a reference sample."], ["Mill matching", "Shanghai office", "Mills shortlisted by construction, fibre and finish capability. Relationship type stated per option."], ["Sampling", "Shanghai office", "Lab dips, strike-offs and functional strike-offs against your approved references."], ["Order & inline inspection", "Mill + YOU LI QA", "Production with inline inspection at the source mill against your acceptance criteria."], ["Pre-shipment verification", "YOU LI QA", "Final checks — weight, width, colour, count, labels, packaging — with a documented report."], ["Import & local delivery", "Uttara office", "Import, customs coordination and delivery to your factory or warehouse in Bangladesh."]];
const performance = [["Uniforms & hygiene", "Antibacterial efficacy", "ISO 20743 / ISO 22196 family", "Tested to buyer specification", "test"], ["Workwear & outerwear", "Water resistance", "AATCC 42 / ISO 4920", "Tested to buyer specification", "test"], ["Protective workwear", "Flame performance", "NFPA 2112 / EN-type", "Tested to buyer specification", "test"], ["Tactical & protective", "Tensile / tear strength", "ISO 13935 / ISO 13937 family", "Tested to buyer specification", "test"], ["Sustainable programs", "Recycled content", "Chain-of-custody documentation", "Verification in progress", "progress"], ["Activewear & swim", "Wicking / UPF", "AATCC 1979 / ASTM D3686", "Tested to buyer specification", "test"]];
const featured = [["Poplin", "Woven Fabrics", "woven", "100% cotton, CVC 60/40, TC 65/35, 100% polyester", "90–160 GSM (approx. 3.5–6 oz)", "/products/woven-fabrics/poplin/"], ["Interlock", "Knit Fabrics", "knit", "100% cotton, CVC, TC, polyester, + elastane", "180–360 GSM", "/products/knit-fabrics/interlock/"], ["Regular Denim", "Denim Fabrics", "denim", "100% cotton, TC 65/35, + elastane options", "6.0–14.5 oz (200–490 GSM)", "/products/denim-fabrics/regular/"], ["Yoga Fabric", "Sportswear & Activewear", "activewear", "Polyamide/elastane, polyester/elastane", "180–280 GSM", "/products/sportswear-activewear/yoga/"], ["Waterproof Fabric", "Functional & Technical", "functional", "Nylon, polyester, blended shells", "90–220 GSM", "/products/functional-technical/waterproof/"], ["Coolmax® Type Yarn", "Functional / Performance Yarns", "yarns", "Capillary (wicking) cross-section", "Polyester staple", "/products/performance-yarns/coolmax/"]];
const faqs = [["What is your MOQ?", "MOQ varies by construction, colour and source mill. We confirm the exact MOQ with every mill-matched option we return — it is never a website number."], ["How does sampling work?", "Send a brief or a reference sample. We return lab dips, strike-offs or functional strike-offs with a written specification comparison, ready for your approval."], ["What data do you need from me?", "Construction, target composition, weight, width, finish, quantity, application, destination and timeline. Anything you do not know, mark “need guidance”."], ["How is quality checked?", "Two stages: inline inspection at the source mill and final pre-shipment verification, both against acceptance criteria you approve, both documented."], ["Which origins do you source from?", "China is our active, documented sourcing region. Asia and Europe coverage is described in company materials and is being verified region by region."], ["What do you need to show me before I commit?", "Specification comparison, sample, inspection plan and — where the program requires it — certificate metadata."]];

export default function Home({ images }: { images: Images }) {
  return <div>
    <section className="hero hero-home"><div className="hero-home-media"><img src={images.hero} alt="Conceptual macro fabric texture" /></div><div className="container hero-inner"><div className="hero-copy"><p className="eyebrow">China-Connected Sourcing · Bangladesh Apparel Support</p><h1>Fabric sourcing that connects China supply with Bangladesh execution</h1><p className="lead">Woven, knit, denim and performance materials matched to your specification, with buyer-facing quality checks at the source mill and before shipment — and delivery coordination from our Uttara, Dhaka office.</p><div className="hero-actions"><Link className="btn btn-primary" href="/request-a-quote/">Request a Fabric Match</Link><Link className="btn btn-ghost" href="/products/">Browse the Fabric Library</Link></div></div></div><div className="proof-strip"><div className="container proof-inner">{[["Bangladesh office", "Uttara, Dhaka"], ["China office", "Shanghai"], ["Woven", "8 constructions"], ["Knit", "7 constructions"], ["Denim", "5 constructions"], ["Performance", "Fabrics & yarns"]].map(([a, b]) => <span className="proof-item" key={a}><b>{a}</b>{b}<Pill>Company statement</Pill></span>)}</div></div></section>
    <section className="sec"><div className="container"><Head n="01">Where you are coming from</Head><div className="path-grid">{paths.map(([a, b, c, href]) => <Link className="path-card" href={href} key={a}><span className="path-t">{a}</span><span className="path-s">{b}</span><span className="path-c">{c}</span></Link>)}</div></div></section>
    <section className="sec sec-paper"><div className="container"><Head n="02">The categories</Head><div className="cat-grid">{cats.map(([name, meta, key, href]) => <Link className="cat-card" href={href} key={name}><span className="cat-media"><img src={images[key]} alt="" loading="lazy" /></span><span className="cat-name">{name}</span><span className="cat-meta">{meta}</span></Link>)}</div></div></section>
    <section className="sec"><div className="container"><Head n="03">Why YOU LI</Head><div className="why-grid">{why.map(([title, copy], i) => <div className="why-card" key={title}><span className="why-n">0{i + 1}</span><h3>{title}</h3><p>{copy}</p><Pill>Company statement</Pill></div>)}</div></div></section>
    <section className="sec sec-ink"><div className="container"><Head n="04" lead="Six steps, a named owner per step, an artifact at each handoff. The route is the product.">The China-to-Bangladesh route</Head><ol className="route-grid">{route.map(([title, owner, copy], i) => <li className="route-card" key={title}><span className="route-n">{i + 1}</span><h3>{title}</h3><p className="route-owner">{owner}</p><p>{copy}</p></li>)}</ol><Link className="link-ghost light" href="/services/sourcing-process/">The full process with artifacts →</Link></div></section>
    <section className="sec"><div className="container"><Head n="05">Quality, as a process with documents</Head><div className="split"><div className="prose"><p>Two gates, both documented: <strong>inline inspection at the source mill</strong> while the fabric is being made, and <strong>pre-shipment verification</strong> before the container seals. Both run against acceptance criteria you approve; both produce reports you and your factory both hold.</p><p>There is no “zero defect” claim on this site — the process is the claim. The findings log and the verification report are the evidence, dated and in the order file.</p><p className="split-links"><Link href="/quality-compliance/quality-assurance/">Quality Assurance →</Link><Link href="/quality-compliance/certifications-compliance/">Certifications & the evidence register →</Link></p></div><figure className="split-media"><img src={images.inspection} alt="Conceptual quality inspection" loading="lazy" /><figcaption>Conceptual imagery — not a depiction of real operations</figcaption></figure></div></div></section>
    <section className="sec sec-paper"><div className="container"><Head n="06" lead="Functional claims are testable properties. Methods are agreed per program; results are delivered against your acceptance targets.">Performance matrix</Head><div className="table-wrap"><table><thead><tr><th>Application</th><th>Property</th><th>Reference method</th><th>Evidence status</th></tr></thead><tbody>{performance.map(([a, b, c, d, tone]) => <tr key={a}><td>{a}</td><td>{b}</td><td>{c}</td><td><Pill tone={tone}>{d}</Pill></td></tr>)}</tbody></table></div></div></section>
    <section className="sec"><div className="container"><Head n="07">Sustainability, evidence-coded</Head><div className="state-grid">{[["Certified", "Materials with current, documented certification. Evidence is published with issuer, scope and validity — no badge without the document."], ["Claim-level", "Materials where the supplier claim exists but documentation is still being assembled. Labeled as such, never published as certified."], ["In verification", "Materials in the evidence process — transaction certificates and chain-of-custody documents requested and tracked."]].map(([title, copy]) => <div className="state-card" key={title}><h3>{title}</h3><p>{copy}</p></div>)}</div><p className="split-links"><Link href="/quality-compliance/sustainability/">The sustainability page →</Link><Link href="/products/functional-technical/recycled/">Recycled fabric record →</Link></p></div></section>
    <section className="sec sec-paper"><div className="container"><Head n="08">Featured records from the library</Head><div className="feat-grid">{featured.map(([name, cat, key, comp, weight, href]) => <Link className="feat-card" href={href} key={name}><span className="feat-media"><img src={images[key]} alt="" loading="lazy" /><span className="feat-cat">{cat}</span></span><span className="feat-body"><span className="feat-name">{name}</span><span className="feat-chips"><i><b>Composition</b>{comp}</i><i><b>Weight</b>{weight}</i></span><span className="feat-cta">Full record →</span></span></Link>)}</div><p className="split-links"><Link href="/products/">Browse all 36 records →</Link></p></div></section>
    <section className="sec"><div className="container"><Head n="09">How it works, in one screen</Head><div className="proc-strip">{["Brief", "Match", "Sample", "Approve", "Verify", "Deliver"].map((x, i) => <Link className="proc-step" href="/services/sourcing-process/" key={x}><span>0{i + 1}</span>{x}</Link>)}</div></div></section>
    <section className="sec sec-paper"><div className="container"><Head n="10">Questions, answered directly</Head><div className="faq">{faqs.map(([q, a]) => <details className="faq-item" key={q}><summary>{q}<span className="faq-chev" /></summary><div className="faq-a"><p>{a}</p></div></details>)}</div></div></section>
    <section className="cta-band"><div className="container cta-inner"><div className="cta-copy"><h2>The first answer you get is the evidence</h2><p>Send one construction or a reference sample. Options return with relationship types, specification comparisons, MOQ and dated lead times — and the quality plan for each.</p></div><div className="cta-actions"><Link className="btn btn-bronze" href="/request-a-quote/">Request a Fabric Match</Link><Link className="btn btn-ghost" href="/contact/">Or talk to the team</Link></div></div></section>
  </div>;
}
